# Generated by Django 3.1.6 on 2021-02-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='user',
            new_name='owner',
        ),
    ]
